// Next.js
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

// tRPC
import { api } from "../utils/api";

// Mantine
import { Button } from "@mantine/core";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-2xl text-blue-300">
        {hello.data ? hello.data.greeting : "Loading tRPC query..."}
      </div>
      <Link href="/value">
        <Button className="text-2xl text-blue-300">
          value(名前は適当)ページに移動
        </Button>
      </Link>
    </>
  );
};

export default Home;
